import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Expanded dataset (200 samples)
data = [
    ["I'm over the moon right now!", "joy"],
    ["This is absolutely infuriating!", "anger"],
    ["I feel so empty inside...", "sadness"],
    ["What a serene evening by the lake.", "peace"],
    ["I'm terrified of what might happen.", "fear"],
    ["Thank you for everything you’ve done.", "gratitude"],
    ["I’m so stressed I can’t think straight.", "stress"],
    ["This surprise made my entire week!", "joy"],
    ["Why does everyone ignore me?", "sadness"],
    ["I’m boiling with rage right now.", "anger"],
    ["Finally, some quiet time to myself.", "peace"],
    ["My heart won’t stop pounding.", "fear"],
    ["I appreciate you more than you know.", "gratitude"],
    ["The workload is crushing me.", "stress"],
    ["Best news I’ve heard all year!", "joy"],
    ["I can’t deal with this nonsense anymore.", "anger"],
    ["I just want to disappear forever.", "sadness"],
    ["The sound of rain is so calming.", "peace"],
    ["What if I fail? I can’t handle it.", "fear"],
    ["I’m so lucky to have you in my life.", "gratitude"],
    ["I’m drowning in deadlines.", "stress"],
    ["Woo-hoo! I got the job!", "joy"],
    ["You’re driving me up the wall!", "anger"],
    ["Nothing brings me joy anymore.", "sadness"],
    ["Meditation clears my mind.", "peace"],
    ["I’m scared to even try.", "fear"],
    ["You’re a lifesaver. Thank you.", "gratitude"],
    ["I’m on the verge of a breakdown.", "stress"],
    ["This is pure bliss!", "joy"],
    ["I’m so fed up with this!", "anger"],
    ["Tears won’t stop flowing today.", "sadness"],
    ["The ocean waves soothe my soul.", "peace"],
    ["I’m paralyzed with anxiety.", "fear"],
    ["I owe you so much.", "gratitude"],
    ["I can’t keep up with everything.", "stress"],
    ["I’m grinning from ear to ear!", "joy"],
    ["I could scream right now!", "anger"],
    ["Why does life hurt so much?", "sadness"],
    ["The mountains bring me peace.", "peace"],
    ["I’m shaking with fear.", "fear"],
    ["Your kindness means the world.", "gratitude"],
    ["I’m stretched too thin.", "stress"],
    ["Today couldn’t get any better!", "joy"],
    ["I’m seeing red right now.", "anger"],
    ["I’m drowning in sadness.", "sadness"],
    ["A warm cup of tea fixes everything.", "peace"],
    ["I’m haunted by my thoughts.", "fear"],
    ["I’ll never forget your help.", "gratitude"],
    ["The pressure is unbearable.", "stress"],
    ["I’m bursting with happiness!", "joy"],
    ["I’m about to lose my temper.", "anger"],
    ["My heart is heavy today.", "sadness"],
    ["The forest is my sanctuary.", "peace"],
    ["I’m too scared to move.", "fear"],
    ["You’ve restored my faith in people.", "gratitude"],
    ["I’m collapsing under pressure.", "stress"],
    ["Life is beautiful today!", "joy"],
    ["I’m seething with anger.", "anger"],
    ["I’m numb from the pain.", "sadness"],
    ["Yoga helps me find balance.", "peace"],
    ["I’m terrified of the future.", "fear"],
    ["I’m forever grateful.", "gratitude"],
    ["I’m drowning in responsibilities.", "stress"],
    ["I’m on cloud nine!", "joy"],
    ["I’m furious beyond words.", "anger"],
    ["I’m broken beyond repair.", "sadness"],
    ["The sunset melts my worries away.", "peace"],
    ["I’m frozen with dread.", "fear"],
    ["You’re my hero.", "gratitude"],
    ["I’m buried in work.", "stress"],
    ["This is a dream come true!", "joy"],
    ["I’m about to explode!", "anger"],
    ["I’m lost in darkness.", "sadness"],
    ["The silence is golden.", "peace"],
    ["I’m petrified of what’s next.", "fear"],
    ["I can’t thank you enough.", "gratitude"],
    ["I’m at my breaking point.", "stress"],
    ["I’m beaming with pride!", "joy"],
    ["I’m boiling over with rage.", "anger"],
    ["I’m a prisoner of my sorrow.", "sadness"],
    ["The garden is my happy place.", "peace"],
    ["I’m trembling with fear.", "fear"],
    ["Your generosity overwhelms me.", "gratitude"],
    ["I’m suffocating from stress.", "stress"],
    ["I’m jumping for joy!", "joy"],
    ["I’m livid right now!", "anger"],
    ["I’m drowning in tears.", "sadness"],
    ["The stars calm my mind.", "peace"],
    ["I’m terrified of failing.", "fear"],
    ["You’ve changed my life.", "gratitude"],
    ["I’m crumbling under stress.", "stress"],
    ["I’m overjoyed beyond words!", "joy"],
    ["I’m fuming with anger.", "anger"],
    ["I’m shattered inside.", "sadness"],
    ["The breeze is so refreshing.", "peace"],
    ["I’m scared to death.", "fear"],
    ["I’m indebted to you.", "gratitude"],
    ["I’m drowning in chaos.", "stress"],
    ["This is pure euphoria!", "joy"],
    ["I’m about to snap!", "anger"],
    ["I’m a wreck emotionally.", "sadness"],
    ["The river’s flow is so peaceful.", "peace"],
    ["I’m panicking uncontrollably.", "fear"],
    ["You’re my guardian angel.", "gratitude"],
    ["I’m buried alive in work.", "stress"],
    ["I’m ecstatic!", "joy"],
    ["I’m seeing stars from anger.", "anger"],
    ["I’m hollow inside.", "sadness"],
    ["The sound of birds is divine.", "peace"],
    ["I’m scared out of my wits.", "fear"],
    ["I’ll cherish this forever.", "gratitude"],
    ["I’m a stress ball.", "stress"],
    ["I’m thrilled to bits!", "joy"],
    ["I’m burning with fury.", "anger"],
    ["I’m a shadow of myself.", "sadness"],
    ["The candlelight is so soothing.", "peace"],
    ["I’m quaking in my boots.", "fear"],
    ["You’ve saved me.", "gratitude"],
    ["I’m a pressure cooker.", "stress"],
    ["I’m walking on sunshine!", "joy"],
    ["I’m ready to punch something.", "anger"],
    ["I’m a puddle of misery.", "sadness"],
    ["The aroma of lavender relaxes me.", "peace"],
    ["I’m scared stiff.", "fear"],
    ["You’re a blessing.", "gratitude"],
    ["I’m a stress magnet.", "stress"],
    ["I’m buzzing with excitement!", "joy"],
    ["I’m in a blind rage.", "anger"],
    ["I’m a storm of sadness.", "sadness"],
    ["The sound of crickets is peaceful.", "peace"],
    ["I’m shaking like a leaf.", "fear"],
    ["You’ve given me hope.", "gratitude"],
    ["I’m a walking panic attack.", "stress"],
    ["I’m on top of the world!", "joy"],
    ["I’m a volcano of anger.", "anger"],
    ["I’m a well of despair.", "sadness"],
    ["The snowfall is so tranquil.", "peace"],
    ["I’m scared beyond belief.", "fear"],
    ["You’re my miracle.", "gratitude"],
    ["I’m a stress tornado.", "stress"],
    ["I’m floating with happiness!", "joy"],
    ["I’m a ticking time bomb.", "anger"],
    ["I’m a river of tears.", "sadness"],
    ["The sound of wind chimes is heavenly.", "peace"],
    ["I’m a bundle of nerves.", "fear"],
    ["You’re my rock.", "gratitude"],
    ["I’m a stress volcano.", "stress"],
    ["I’m glowing with joy!", "joy"],
    ["I’m a fireball of rage.", "anger"],
    ["I’m a black hole of sadness.", "sadness"],
    ["The sound of a waterfall is serene.", "peace"],
    ["I’m a scaredy-cat.", "fear"],
    ["You’re my savior.", "gratitude"],
    ["I’m a stress hurricane.", "stress"],
    ["I’m radiating happiness!", "joy"],
    ["I’m a powder keg of anger.", "anger"],
    ["I’m a desert of sorrow.", "sadness"],
    ["The sound of leaves rustling is calming.", "peace"],
    ["I’m a nervous wreck.", "fear"],
    ["You’re my sunshine.", "gratitude"],
    ["I’m a stress tsunami.", "stress"],
    ["I’m sparkling with joy!", "joy"],
    ["I’m a furnace of fury.", "anger"],
    ["I’m a graveyard of emotions.", "sadness"],
    ["The sound of a purring cat is bliss.", "peace"],
    ["I’m a scared little mouse.", "fear"],
    ["You’re my everything.", "gratitude"],
    ["I’m a stress avalanche.", "stress"],
    ["I’m shining with delight!", "joy"],
    ["I’m a wildfire of anger.", "anger"],
    ["I’m a ship lost at sea.", "sadness"],
    ["The sound of a harp is ethereal.", "peace"],
    ["I’m a trembling rabbit.", "fear"],
    ["You’re my knight in shining armor.", "gratitude"],
    ["I’m a stress earthquake.", "stress"],
    ["I’m beaming with joy!", "joy"],
    ["I’m a tornado of rage.", "anger"],
    ["I’m a wilted flower.", "sadness"],
    ["The sound of silence is golden.", "peace"],
    ["I’m a quivering mess.", "fear"],
    ["You’re my guiding light.", "gratitude"],
    ["I’m a stress inferno.", "stress"],
    ["I’m glowing with glee!", "joy"],
    ["I’m a storm of fury.", "anger"],
    ["I’m a broken mirror.", "sadness"],
    ["The sound of waves is hypnotic.", "peace"],
    ["I’m a scared little bird.", "fear"],
    ["You’re my angel.", "gratitude"],
    ["I’m a stress monster.", "stress"],
]

# Separate texts and labels
texts = [item[0] for item in data]
labels = [item[1] for item in data]

# Train-test split (80-20)
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

# Vectorization
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Model training
model = LogisticRegression(max_iter=1000)  # Increased max_iter for convergence
model.fit(X_train_vec, y_train)

# Evaluate
y_pred = model.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Model trained! Accuracy: {accuracy:.2f}")

# Save artifacts
joblib.dump(model, "mood_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")
print("Model and vectorizer saved!")